Semicolons cleanup

diff --git a/pull_all b/pull_all
--- a/pull_all
+++ b/pull_all
@@ -18,28 +18,28 @@
 for arg in "$@"; do
     shift
     case "$arg" in
-        "--dir")            set -- "$@" "-d" ;;
-        "--help")           set -- "$@" "-h" ;;
-        "--write-remotes")  set -- "$@" "-w" ;;
-        "--prune")          set -- "$@" "-p" ;;
-        "--submodules")     set -- "$@" "-s" ;;
-        "--remotes-file")   set -- "$@" "-f" ;;
-        "--local-branches") set -- "$@" "-l" ;;
-        "--recursive")      set -- "$@" "-r" ;;
-        "--push")           set -- "$@" "-P" ;;
-        *)                  set -- "$@" "$arg" ;;
+        "--dir")            set -- "$@" "-d";;
+        "--help")           set -- "$@" "-h";;
+        "--write-remotes")  set -- "$@" "-w";;
+        "--prune")          set -- "$@" "-p";;
+        "--submodules")     set -- "$@" "-s";;
+        "--remotes-file")   set -- "$@" "-f";;
+        "--local-branches") set -- "$@" "-l";;
+        "--recursive")      set -- "$@" "-r";;
+        "--push")           set -- "$@" "-P";;
+        *)                  set -- "$@" "$arg";;
     esac
 done
 
 
 # defaults
-DIRS=();
-HELP=0;
-WRITE_REMOTES=0;
-REMOTES_FILE="git_remotes.sh";
-PRUNE=0;
-SUBMODULES=0;
-LOCAL_BRANCHES_UPDATE=0;
+DIRS=()
+HELP=0
+WRITE_REMOTES=0
+REMOTES_FILE="git_remotes.sh"
+PRUNE=0
+SUBMODULES=0
+LOCAL_BRANCHES_UPDATE=0
 RECURSIVE=0
 PUSH=0
 
@@ -65,22 +65,22 @@ while getopts 'd:hwpPslrf:' opt; do
            ;;
         P) PUSH=1
            ;;
-        \?) echo "Unknown option: -$OPTARG" >&2;
+        \?) echo "Unknown option: -$OPTARG" >&2
              exit 1
              ;;
-        :) echo "Missing option argument for -$OPTARG" >&2;
+        :) echo "Missing option argument for -$OPTARG" >&2
             exit 1
             ;;
-        *) echo "Unimplemented option: -$OPTARG" >&2;
+        *) echo "Unimplemented option: -$OPTARG" >&2
             exit 1
             ;;
     esac
 done
 
 
-shift "$((OPTIND-1))";
+shift "$((OPTIND-1))"
 # params after '--' to ARGV
-[ "${1:-}" = "--" ] && shift;
+[ "${1:-}" = "--" ] && shift
 
 
 if [ "$HELP" -eq 1 ]; then
@@ -120,24 +120,24 @@ Examples:\n
     With specified dir\n
     pull_all --dir  /home/user/gitrepos --dir /home/user/github_repos\n
 EOF
-         );
-    echo $USAGE;
-    exit 0;
+         )
+    echo $USAGE
+    exit 0
 fi
 
 
 # dir option must have
 DIRS_LEN=${#DIRS[@]}
 if [ $DIRS_LEN -lt 1 ]; then
-    echo "Mandatory argument(s) -d (--dir) missing" >&2;
-    exit 1;
+    echo "Mandatory argument(s) -d (--dir) missing" >&2
+    exit 1
 fi
 
 # validate dirs exists
 for path in "${DIRS[@]}"; do
     if [ ! -d "$path" ]; then
-        echo -e "\033[91mDir [$path] not found, nothing to do!\033[0m";
-        exit 1;
+        echo -e "\033[91mDir [$path] not found, nothing to do!\033[0m"
+        exit 1
     else
         case "$path" in
             /*) printf '%s to update\n' "$path"
@@ -150,9 +150,9 @@ done
 
 main() {
     if [ "$RECURSIVE" -eq 1 ]; then
-        recursive;
+        recursive
     else
-        depth1;
+        depth1
     fi
 }
 
@@ -163,28 +163,28 @@ depth1() {
     # collect repo links and write sh file as ready to git clone command
     # NOTE: works only with 'origin' remote name
     if [ "$WRITE_REMOTES" -eq 1 ]; then
-        echo "Collecting repos links, writing to clone...";
-        echo "#!/bin/bash" > $REMOTES_FILE;
+        echo "Collecting repos links, writing to clone..."
+        echo "#!/bin/bash" > $REMOTES_FILE
         for DIR in "${DIRS[@]}"; do
             find $DIR -maxdepth 1 -type d -not -path "." -not -path ".." -not -path "$DIR" \
                 | sort | uniq | \
-                xargs -I % sh -c 'FILE="%"; echo "git clone $(git -C $DIR/$FILE remote get-url origin)"' >> $REMOTES_FILE;
+                xargs -I % sh -c 'FILE="%"; echo "git clone $(git -C $DIR/$FILE remote get-url origin)"' >> $REMOTES_FILE
         done
-        chmod +x $REMOTES_FILE;
-        exit 0;
+        chmod +x $REMOTES_FILE
+        exit 0
     fi
 
 
     # push and exit, use separate from pull
     if [ "$PUSH" -eq 1 ]; then
         # push to upstream
-        echo -e "\033[92mPushing branches to upstream...\033[0m";
+        echo -e "\033[92mPushing branches to upstream...\033[0m"
         for DIR in "${DIRS[@]}"; do
             find $DIR -maxdepth 1 -type d -not -path "." -not -path ".." -not -path "$DIR" \
                  -exec sh -c 'echo Path: {}; true' \; \
                  -exec git --git-dir={}/.git --work-tree={} push \; 2>/dev/null
         done
-        exit 0;
+        exit 0
     fi
 
     # INFO: sequential operations
@@ -194,7 +194,7 @@ depth1() {
         # -exec sh -c 'echo Path: $DIR/{}; true' \; -exec git -C {} pull --prune --no-edit --all \;
 
     # update main repositories (always)
-    echo -e "\033[92mUpdating repositories...\033[0m";
+    echo -e "\033[92mUpdating repositories...\033[0m"
     for DIR in "${DIRS[@]}"; do
         find $DIR -maxdepth 1 -type d -not -path "." -not -path ".." -not -path "$DIR" \
              -exec sh -c 'echo Path: {}; true' \; \
@@ -215,8 +215,8 @@ depth1() {
 
     # submodules update (-s arg)
     if [ "$SUBMODULES" -eq 1 ]; then
-        echo -e "\033[91mUpdating submodules...\033[0m";
-        SED="sed";
+        echo -e "\033[91mUpdating submodules...\033[0m"
+        SED="sed"
         case "$OSTYPE" in
             *darwin*)
                 SED="gsed"
@@ -228,7 +228,7 @@ depth1() {
         for DIR in "${DIRS[@]}"; do
             find $DIR -type f -name '.gitmodules' \
                 | $SED -r 's|/[^/]+$||' | sort | uniq \
-                | xargs -I % sh -c 'FILE="%"; echo Path: $FILE; git -C $FILE submodule update --remote --recursive --merge'; 2>/dev/null
+                | xargs -I % sh -c 'FILE="%"; echo Path: $FILE; git -C $FILE submodule update --remote --recursive --merge' 2>/dev/null
         done
     fi
 
@@ -246,7 +246,7 @@ depth1() {
 # can be dangerous to use!
 recursive() {
     # TODO: implement prune, submodules, remotes write, push etc.
-    echo -e "\033[92mFinding and updating repositories recursively...\033[0m";
+    echo -e "\033[92mFinding and updating repositories recursively...\033[0m"
     for DIR in "${DIRS[@]}"; do
         find $DIR -type d -name ".git" \
              -exec sh -c 'echo Path: {}; true' \; \
@@ -257,28 +257,28 @@ recursive() {
 
 # a ffwd local branches update to their remotes func
 git_ffwd() {
-    REPO="$1";
-    REMOTES=$(git --git-dir=$REPO/.git --work-tree=$REPO remote);
-    REMOTES=$(echo "$REMOTES" | xargs -n1 echo);
-    CLB=$(git --git-dir=$REPO/.git --work-tree=$REPO rev-parse --abbrev-ref HEAD);
+    REPO="$1"
+    REMOTES=$(git --git-dir=$REPO/.git --work-tree=$REPO remote)
+    REMOTES=$(echo "$REMOTES" | xargs -n1 echo)
+    CLB=$(git --git-dir=$REPO/.git --work-tree=$REPO rev-parse --abbrev-ref HEAD)
     echo "$REMOTES" | while read REMOTE; do
-        git --git-dir=$REPO/.git --work-tree=$REPO remote update $REMOTE;
+        git --git-dir=$REPO/.git --work-tree=$REPO remote update $REMOTE
         git --git-dir=$REPO/.git --work-tree=$REPO remote show $REMOTE -n \
             | awk '/merges with remote/{print $5" "$1}' \
             | while read RB LB; do
-            ARB="refs/remotes/$REMOTE/$RB";
-            ALB="refs/heads/$LB";
-            NBEHIND=$(( $(git --git-dir=$REPO/.git --work-tree=$REPO rev-list --count $ALB..$ARB 2>/dev/null) +0));
-            NAHEAD=$(( $(git --git-dir=$REPO/.git --work-tree=$REPO rev-list --count $ARB..$ALB 2>/dev/null) +0));
+            ARB="refs/remotes/$REMOTE/$RB"
+            ALB="refs/heads/$LB"
+            NBEHIND=$(( $(git --git-dir=$REPO/.git --work-tree=$REPO rev-list --count $ALB..$ARB 2>/dev/null) +0))
+            NAHEAD=$(( $(git --git-dir=$REPO/.git --work-tree=$REPO rev-list --count $ARB..$ALB 2>/dev/null) +0))
             if [ "$NBEHIND" -gt 0 ]; then
                 if [ "$NAHEAD" -gt 0 ]; then
-                    echo -e "\033[34mBranch $LB is $NBEHIND commit(s) behind and $NAHEAD commit(s) ahead of $REMOTE/$RB. Could not be fast-forwarded\033[0m";
+                    echo -e "\033[34mBranch $LB is $NBEHIND commit(s) behind and $NAHEAD commit(s) ahead of $REMOTE/$RB. Could not be fast-forwarded\033[0m"
                 elif [ "$LB" = "$CLB" ]; then
                     echo -e "\033[34mBranch $LB was $NBEHIND commit(s) behind of $REMOTE/$RB. Fast-forward merge\033[0m";
-                    git --git-dir=$REPO/.git --work-tree=$REPO merge -q $ARB;
+                    git --git-dir=$REPO/.git --work-tree=$REPO merge -q $ARB
                 else
-                    echo -e "\033[34mBranch $LB was $NBEHIND commit(s) behind of $REMOTE/$RB. Resetting local branch to remote\033[0m";
-                    git --git-dir=$REPO/.git --work-tree=$REPO branch -f $LB -t $ARB >/dev/null;
+                    echo -e "\033[34mBranch $LB was $NBEHIND commit(s) behind of $REMOTE/$RB. Resetting local branch to remote\033[0m"
+                    git --git-dir=$REPO/.git --work-tree=$REPO branch -f $LB -t $ARB >/dev/null
                 fi
             fi
         done
@@ -286,6 +286,6 @@ git_ffwd() {
 }
 
 # 'bash' required to export functions
-export -f git_ffwd;
+export -f git_ffwd
 
-main "$@";
+main "$@"
